In [ ]:
from google.colab import drive
drive.mount('/content/drive',force_remount=True)

Mounted at /content/drive

In [ ]:
# liste du répertoire
!ls "/content/drive/MyDrive/Accidents/datas/Regroupement"

drive = True
path = "/content/drive/MyDrive/Accidents/"
pathData = "/content/drive/MyDrive/Accidents/datas/Regroupement/"

Accidents_2005_to_2023.csv		 Caracteristiques_lieux_Usagers_2005_to_2023.csv
caracteristiques_2005_to_2023.csv	 Caracteristiques_Usagers_2005_to_2023.csv
caracteristiques_2005_to_2023_step1.csv  lieux_2005_to_2023.csv
caracteristiques_2005_to_2023_step2.csv  usagers_2005_to_2023.csv
Caracteristiques_lieux_2005_to_2023.csv  vehicules_2005_to_2023.csv

In [ ]:
#Import librairies
import pandas as pd
import numpy as np

In [ ]:
# Dataset correspondance région département France
communes_departement_region = pd.read_csv(path + 'communes-departement-region.csv', sep=',')

# Chargement dataset Global
df_caracteristiques =pd.read_csv(pathData + 'caracteristiques_2005_to_2023_step1.csv', sep=',',low_memory=False)

In [ ]:
df_caracteristiques.shape

(1187862, 18)

In [ ]:
df_caracteristiques.head()

,Num_Acc,jour,mois,an,hrmn,lum,dep,com,agg,int,atm,col,adr,lat,long,gps,com_insee_temp,com_insee
0,202300000001,7,5,2023,06:00,1,75.0,75101,2,4,2.0,7.0,RUE DE RIVOLI,"48,86638600","2,32347100",NaN,75.075101,75101
1,202300000002,7,5,2023,05:30,5,94.0,94080,2,1,3.0,6.0,Avenue de Paris,"48,84547782","2,42868146",NaN,94.094080,94080
2,202300000003,7,5,2023,20:50,1,94.0,94022,2,3,2.0,1.0,Avenue du Général Leclerc,"48,76240000","2,40655000",NaN,94.094022,94022
3,202300000004,6,5,2023,23:57,5,94.0,94078,2,1,3.0,5.0,Rue de Paris,"48,73248432","2,44687575",NaN,94.094078,94078
4,202300000005,7,5,2023,00:50,5,94.0,94068,2,2,3.0,3.0,56bis Avenue Raspail,"48,78581000","2,49217000",NaN,94.094068,94068

In [ ]:
df_caracteristiques[df_caracteristiques.com_insee.notnull()].count()

Num_Acc           1187862
jour              1187862
mois              1187862
an                1187862
hrmn              1187862
lum               1187862
dep               1187862
com               1187860
agg               1187862
int               1187862
atm               1187823
col               1187851
adr               1047107
lat                715631
long               715627
gps                463488
com_insee_temp    1187862
com_insee         1187862
dtype: int64

In [ ]:
communes_departement_region.head()

,code_commune_INSEE,nom_commune_postal,code_postal,libelle_acheminement,ligne_5,latitude,longitude,code_commune,article,nom_commune,nom_commune_complet,code_departement,nom_departement,code_region,nom_region
0,1001,L ABERGEMENT CLEMENCIAT,1400,L ABERGEMENT CLEMENCIAT,NaN,46.153426,4.926114,1.0,L',Abergement-Clémenciat,L'Abergement-Clémenciat,1,Ain,84.0,Auvergne-Rhône-Alpes
1,1002,L ABERGEMENT DE VAREY,1640,L ABERGEMENT DE VAREY,NaN,46.009188,5.428017,2.0,L',Abergement-de-Varey,L'Abergement-de-Varey,1,Ain,84.0,Auvergne-Rhône-Alpes
2,1004,AMBERIEU EN BUGEY,1500,AMBERIEU EN BUGEY,NaN,45.960848,5.372926,4.0,NaN,Ambérieu-en-Bugey,Ambérieu-en-Bugey,1,Ain,84.0,Auvergne-Rhône-Alpes
3,1005,AMBERIEUX EN DOMBES,1330,AMBERIEUX EN DOMBES,NaN,45.996180,4.912273,5.0,NaN,Ambérieux-en-Dombes,Ambérieux-en-Dombes,1,Ain,84.0,Auvergne-Rhône-Alpes
4,1006,AMBLEON,1300,AMBLEON,NaN,45.749499,5.594320,6.0,NaN,Ambléon,Ambléon,1,Ain,84.0,Auvergne-Rhône-Alpes

In [ ]:
# Renommer la colonne 'departmentCode' en 'dep'
communes_departement_region.rename(columns={'code_departement': 'dep'},inplace=True)
communes_departement_region = communes_departement_region.astype({'dep':'str'})

In [ ]:
communes_departement_region["dep"] = ["00"+_ if len(_) < 2 else "0"+_ if len(_) < 3 else _ for _ in communes_departement_region["dep"].values]

In [ ]:
# Conversion Corse en 20
communes_departement_region['dep'].mask( communes_departement_region['dep'] == '02a', '020' , inplace=True )
communes_departement_region['dep'].mask( communes_departement_region['dep'] == '02b', '020' , inplace=True )

<ipython-input-13-5f130330a6d7>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  communes_departement_region['dep'].mask( communes_departement_region['dep'] == '02a', '020' , inplace=True )
<ipython-input-13-5f130330a6d7>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  communes_departement_region['dep'].mask( communes_departement_region['dep'] == '02b', '020' , inplace=True )

In [ ]:
communes_departement_region.head()

,code_commune_INSEE,nom_commune_postal,code_postal,libelle_acheminement,ligne_5,latitude,longitude,code_commune,article,nom_commune,nom_commune_complet,dep,nom_departement,code_region,nom_region
0,1001,L ABERGEMENT CLEMENCIAT,1400,L ABERGEMENT CLEMENCIAT,NaN,46.153426,4.926114,1.0,L',Abergement-Clémenciat,L'Abergement-Clémenciat,001,Ain,84.0,Auvergne-Rhône-Alpes
1,1002,L ABERGEMENT DE VAREY,1640,L ABERGEMENT DE VAREY,NaN,46.009188,5.428017,2.0,L',Abergement-de-Varey,L'Abergement-de-Varey,001,Ain,84.0,Auvergne-Rhône-Alpes
2,1004,AMBERIEU EN BUGEY,1500,AMBERIEU EN BUGEY,NaN,45.960848,5.372926,4.0,NaN,Ambérieu-en-Bugey,Ambérieu-en-Bugey,001,Ain,84.0,Auvergne-Rhône-Alpes
3,1005,AMBERIEUX EN DOMBES,1330,AMBERIEUX EN DOMBES,NaN,45.996180,4.912273,5.0,NaN,Ambérieux-en-Dombes,Ambérieux-en-Dombes,001,Ain,84.0,Auvergne-Rhône-Alpes
4,1006,AMBLEON,1300,AMBLEON,NaN,45.749499,5.594320,6.0,NaN,Ambléon,Ambléon,001,Ain,84.0,Auvergne-Rhône-Alpes

In [ ]:
communes_departement_region.shape

(39201, 15)

In [ ]:
communes_departement_region["com_insee"] = ["0"+_ if len(_) < 5 else _ for _ in communes_departement_region["code_commune_INSEE"].values]
communes_departement_region = communes_departement_region[["com_insee","nom_commune","dep","nom_departement","code_region","nom_region","latitude","longitude"]].rename(columns={"latitude":"latitude_com","longitude":"longitude_com"})
communes_departement_region = communes_departement_region.drop_duplicates()

In [ ]:
communes_departement_region.head()

,com_insee,nom_commune,dep,nom_departement,code_region,nom_region,latitude_com,longitude_com
0,01001,Abergement-Clémenciat,001,Ain,84.0,Auvergne-Rhône-Alpes,46.153426,4.926114
1,01002,Abergement-de-Varey,001,Ain,84.0,Auvergne-Rhône-Alpes,46.009188,5.428017
2,01004,Ambérieu-en-Bugey,001,Ain,84.0,Auvergne-Rhône-Alpes,45.960848,5.372926
3,01005,Ambérieux-en-Dombes,001,Ain,84.0,Auvergne-Rhône-Alpes,45.996180,4.912273
4,01006,Ambléon,001,Ain,84.0,Auvergne-Rhône-Alpes,45.749499,5.594320

In [ ]:
communes_departement_region.shape

(36013, 8)

In [ ]:
df_caracteristiques.head()

,Num_Acc,jour,mois,an,hrmn,lum,dep,com,agg,int,atm,col,adr,lat,long,gps,com_insee_temp,com_insee
0,202300000001,7,5,2023,06:00,1,75.0,75101,2,4,2.0,7.0,RUE DE RIVOLI,"48,86638600","2,32347100",NaN,75.075101,75101
1,202300000002,7,5,2023,05:30,5,94.0,94080,2,1,3.0,6.0,Avenue de Paris,"48,84547782","2,42868146",NaN,94.094080,94080
2,202300000003,7,5,2023,20:50,1,94.0,94022,2,3,2.0,1.0,Avenue du Général Leclerc,"48,76240000","2,40655000",NaN,94.094022,94022
3,202300000004,6,5,2023,23:57,5,94.0,94078,2,1,3.0,5.0,Rue de Paris,"48,73248432","2,44687575",NaN,94.094078,94078
4,202300000005,7,5,2023,00:50,5,94.0,94068,2,2,3.0,3.0,56bis Avenue Raspail,"48,78581000","2,49217000",NaN,94.094068,94068

In [ ]:
communes_departement_region.dep.unique()

array(['001', '002', '003', '004', '005', '006', '007', '008', '009',
       '010', '011', '012', '013', '014', '015', '016', '017', '018',
       '019', '021', '022', '023', '024', '025', '026', '027', '028',
       '029', '02A', '02B', '030', '031', '032', '033', '034', '035',
       '036', '037', '038', '039', '040', '041', '042', '043', '044',
       '045', '046', '047', '048', '049', '050', '051', '052', '053',
       '054', '055', '056', '057', '058', '059', '060', '061', '062',
       '063', '064', '065', '066', '067', '068', '069', '070', '071',
       '072', '073', '074', '075', '076', '077', '078', '079', '080',
       '081', '082', '083', '084', '085', '086', '087', '088', '089',
       '090', '091', '092', '093', '094', '095', '971', '972', '973',
       '974', '097', '976', '098', 'nan', '099'], dtype=object)

In [ ]:
# Conversion Corse en 20
communes_departement_region['dep'].mask( communes_departement_region['dep'] == '02A', '020' , inplace=True )
communes_departement_region['dep'].mask( communes_departement_region['dep'] == '02B', '020' , inplace=True )

<ipython-input-21-759b87216342>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  communes_departement_region['dep'].mask( communes_departement_region['dep'] == '02A', '020' , inplace=True )
<ipython-input-21-759b87216342>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  communes_departement_region['dep'].mask( communes_departement_region['dep'] == '02B', '020' , inplace=True )

In [ ]:
communes_departement_region.dropna(subset=['dep'],inplace=True)

In [ ]:
mask = communes_departement_region['dep'] == 'nan'

# select all rows except the ones that contain 'Coca Cola'
communes_departement_region = communes_departement_region[~mask]

In [ ]:
communes_departement_region = communes_departement_region.astype({'dep':'int'})

In [ ]:
communes_departement_region.head()

,com_insee,nom_commune,dep,nom_departement,code_region,nom_region,latitude_com,longitude_com
0,01001,Abergement-Clémenciat,1,Ain,84.0,Auvergne-Rhône-Alpes,46.153426,4.926114
1,01002,Abergement-de-Varey,1,Ain,84.0,Auvergne-Rhône-Alpes,46.009188,5.428017
2,01004,Ambérieu-en-Bugey,1,Ain,84.0,Auvergne-Rhône-Alpes,45.960848,5.372926
3,01005,Ambérieux-en-Dombes,1,Ain,84.0,Auvergne-Rhône-Alpes,45.996180,4.912273
4,01006,Ambléon,1,Ain,84.0,Auvergne-Rhône-Alpes,45.749499,5.594320

In [ ]:
communes_departement_region_sup = list(communes_departement_region.loc[(communes_departement_region.dep > 950),'com_insee'])
communes_departement_region = communes_departement_region[communes_departement_region["com_insee"].isin(communes_departement_region) == False]

In [ ]:
#971, 972, 973, 974,  97, 976,  98,
mask = communes_departement_region['dep'] == 99
# select all rows except the ones that contain 'Coca Cola'
communes_departement_region = communes_departement_region[~mask]

In [ ]:
communes_departement_region = communes_departement_region.astype({'dep':'str'})

In [ ]:
communes_departement_region.head()

,com_insee,nom_commune,dep,nom_departement,code_region,nom_region,latitude_com,longitude_com
0,01001,Abergement-Clémenciat,1,Ain,84.0,Auvergne-Rhône-Alpes,46.153426,4.926114
1,01002,Abergement-de-Varey,1,Ain,84.0,Auvergne-Rhône-Alpes,46.009188,5.428017
2,01004,Ambérieu-en-Bugey,1,Ain,84.0,Auvergne-Rhône-Alpes,45.960848,5.372926
3,01005,Ambérieux-en-Dombes,1,Ain,84.0,Auvergne-Rhône-Alpes,45.996180,4.912273
4,01006,Ambléon,1,Ain,84.0,Auvergne-Rhône-Alpes,45.749499,5.594320

In [ ]:
communes_departement_region["dep"] = ["0"+_ if len(_) == 1 else _ for _ in communes_departement_region["dep"].values]

In [ ]:
communes_departement_region.head()

,com_insee,nom_commune,dep,nom_departement,code_region,nom_region,latitude_com,longitude_com
0,01001,Abergement-Clémenciat,01,Ain,84.0,Auvergne-Rhône-Alpes,46.153426,4.926114
1,01002,Abergement-de-Varey,01,Ain,84.0,Auvergne-Rhône-Alpes,46.009188,5.428017
2,01004,Ambérieu-en-Bugey,01,Ain,84.0,Auvergne-Rhône-Alpes,45.960848,5.372926
3,01005,Ambérieux-en-Dombes,01,Ain,84.0,Auvergne-Rhône-Alpes,45.996180,4.912273
4,01006,Ambléon,01,Ain,84.0,Auvergne-Rhône-Alpes,45.749499,5.594320

In [ ]:
communes_departement_region.com_insee.unique()

array(['01001', '01002', '01004', ..., '98832', '98833', '98901'],
      dtype=object)

In [ ]:
# Fusion des 2 datasets caracteristiques et communes_regions_departements
df_caracteristiques = df_caracteristiques.merge(communes_departement_region, how="left", on="com_insee")
df_caracteristiques.head()

,Num_Acc,jour,mois,an,hrmn,lum,dep_x,com,agg,int,...,gps,com_insee_temp,com_insee,nom_commune,dep_y,nom_departement,code_region,nom_region,latitude_com,longitude_com
0,202300000001,7,5,2023,06:00,1,75.0,75101,2,4,...,NaN,75.075101,75101,Paris 01,75,Paris,11.0,Île-de-France,48.862630,2.336293
1,202300000002,7,5,2023,05:30,5,94.0,94080,2,1,...,NaN,94.094080,94080,Vincennes,94,Val-de-Marne,11.0,Île-de-France,48.847373,2.437987
2,202300000003,7,5,2023,20:50,1,94.0,94022,2,3,...,NaN,94.094022,94022,Choisy-le-Roi,94,Val-de-Marne,11.0,Île-de-France,48.764315,2.417425
3,202300000004,6,5,2023,23:57,5,94.0,94078,2,1,...,NaN,94.094078,94078,Villeneuve-Saint-Georges,94,Val-de-Marne,11.0,Île-de-France,48.741381,2.448999
4,202300000005,7,5,2023,00:50,5,94.0,94068,2,2,...,NaN,94.094068,94068,Saint-Maur-des-Fossés,94,Val-de-Marne,11.0,Île-de-France,48.799068,2.493865

In [ ]:
df_caracteristiques[df_caracteristiques.latitude_com.notnull()].count()

Num_Acc            258118
jour               258118
mois               258118
an                 258118
hrmn               258118
lum                258118
dep_x              258118
com                258118
agg                258118
int                258118
atm                258118
col                258118
adr                254173
lat                258118
long               258118
gps                     0
com_insee_temp     258118
com_insee          258118
nom_commune        258118
dep_y              258118
nom_departement    258118
code_region        258118
nom_region         258118
latitude_com       258118
longitude_com      258118
dtype: int64

In [ ]:
df_caracteristiques.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1187862 entries, 0 to 1187861
Data columns (total 25 columns):
 #   Column           Non-Null Count    Dtype
---  ------           --------------    -----
 0   Num_Acc          1187862 non-null  int64
 1   jour             1187862 non-null  int64
 2   mois             1187862 non-null  int64
 3   an               1187862 non-null  int64
 4   hrmn             1187862 non-null  object
 5   lum              1187862 non-null  int64
 6   dep_x            1187862 non-null  float64
 7   com              1187860 non-null  object
 8   agg              1187862 non-null  int64
 9   int              1187862 non-null  int64
 10  atm              1187823 non-null  float64
 11  col              1187851 non-null  float64
 12  adr              1047107 non-null  object
 13  lat              715631 non-null   object
 14  long             715627 non-null   object
 15  gps              463488 non-null   object
 16  com_insee_temp   1187862 non-null  object
 17  com_insee        1187862 non-null  object
 18  nom_commune      258124 non-null   object
 19  dep_y            258124 non-null   object
 20  nom_departement  258124 non-null   object
 21  code_region      258124 non-null   float64
 22  nom_region       258124 non-null   object
 23  latitude_com     258118 non-null   float64
 24  longitude_com    258118 non-null   float64
dtypes: float64(6), int64(7), object(12)
memory usage: 226.6+ MB

In [ ]:
print(df_caracteristiques.lat.dtype)
print(df_caracteristiques.long.dtype)

object
object

In [ ]:
df_caracteristiques_complet = df_caracteristiques.copy()

In [ ]:
df_caracteristiques_complet["lat"]=df_caracteristiques_complet["lat"].str.replace(',','.')
df_caracteristiques_complet["long"]=df_caracteristiques_complet["long"].str.replace(',','.')

In [ ]:
df_caracteristiques_complet = df_caracteristiques_complet.astype({'lat':'float'})

In [ ]:
df_caracteristiques_complet["long"] = df_caracteristiques_complet["long"].replace("-", 0).astype(float)

In [ ]:
df_caracteristiques_complet = df_caracteristiques_complet.astype({'long':'float'})

In [ ]:
df_caracteristiques_complet.shape

(1187862, 25)

In [ ]:
df_caracteristiques_complet.head()

,Num_Acc,jour,mois,an,hrmn,lum,dep_x,com,agg,int,...,gps,com_insee_temp,com_insee,nom_commune,dep_y,nom_departement,code_region,nom_region,latitude_com,longitude_com
0,202300000001,7,5,2023,06:00,1,75.0,75101,2,4,...,NaN,75.075101,75101,Paris 01,75,Paris,11.0,Île-de-France,48.862630,2.336293
1,202300000002,7,5,2023,05:30,5,94.0,94080,2,1,...,NaN,94.094080,94080,Vincennes,94,Val-de-Marne,11.0,Île-de-France,48.847373,2.437987
2,202300000003,7,5,2023,20:50,1,94.0,94022,2,3,...,NaN,94.094022,94022,Choisy-le-Roi,94,Val-de-Marne,11.0,Île-de-France,48.764315,2.417425
3,202300000004,6,5,2023,23:57,5,94.0,94078,2,1,...,NaN,94.094078,94078,Villeneuve-Saint-Georges,94,Val-de-Marne,11.0,Île-de-France,48.741381,2.448999
4,202300000005,7,5,2023,00:50,5,94.0,94068,2,2,...,NaN,94.094068,94068,Saint-Maur-des-Fossés,94,Val-de-Marne,11.0,Île-de-France,48.799068,2.493865

In [ ]:
df_caracteristiques_complet[df_caracteristiques_complet.com_insee.notnull()].count()

Num_Acc            1187862
jour               1187862
mois               1187862
an                 1187862
hrmn               1187862
lum                1187862
dep_x              1187862
com                1187860
agg                1187862
int                1187862
atm                1187823
col                1187851
adr                1047107
lat                 715631
long                715627
gps                 463488
com_insee_temp     1187862
com_insee          1187862
nom_commune         258124
dep_y               258124
nom_departement     258124
code_region         258124
nom_region          258124
latitude_com        258118
longitude_com       258118
dtype: int64

In [ ]:
################################
df_caracteristiques_complet["lat"] = np.where(((df_caracteristiques_complet["lat"]==0)
                         | (df_caracteristiques_complet["long"]==0))
                         & (df_caracteristiques_complet["adr"].isnull()), df_caracteristiques_complet["latitude_com"], df_caracteristiques_complet["lat"])
df_caracteristiques_complet["long"] = np.where(((df_caracteristiques_complet["lat"]==0)
                         | (df_caracteristiques_complet["long"]==0))
                         & (df_caracteristiques_complet["adr"].isnull()), df_caracteristiques_complet["longitude_com"], df_caracteristiques_complet["long"])

In [ ]:
df_caracteristiques_complet.head()

,Num_Acc,jour,mois,an,hrmn,lum,dep_x,com,agg,int,...,gps,com_insee_temp,com_insee,nom_commune,dep_y,nom_departement,code_region,nom_region,latitude_com,longitude_com
0,202300000001,7,5,2023,06:00,1,75.0,75101,2,4,...,NaN,75.075101,75101,Paris 01,75,Paris,11.0,Île-de-France,48.862630,2.336293
1,202300000002,7,5,2023,05:30,5,94.0,94080,2,1,...,NaN,94.094080,94080,Vincennes,94,Val-de-Marne,11.0,Île-de-France,48.847373,2.437987
2,202300000003,7,5,2023,20:50,1,94.0,94022,2,3,...,NaN,94.094022,94022,Choisy-le-Roi,94,Val-de-Marne,11.0,Île-de-France,48.764315,2.417425
3,202300000004,6,5,2023,23:57,5,94.0,94078,2,1,...,NaN,94.094078,94078,Villeneuve-Saint-Georges,94,Val-de-Marne,11.0,Île-de-France,48.741381,2.448999
4,202300000005,7,5,2023,00:50,5,94.0,94068,2,2,...,NaN,94.094068,94068,Saint-Maur-des-Fossés,94,Val-de-Marne,11.0,Île-de-France,48.799068,2.493865

In [ ]:
# Sauvegarde dataset
df_caracteristiques_complet.to_csv(pathData + 'caracteristiques_2005_to_2023_step2.csv', index=False)

In [ ]:
df_caracteristique_geocode = df_caracteristiques_complet.loc[((df_caracteristiques_complet["lat"]==0)
                         | (df_caracteristiques_complet["long"]==0)),["lat","long","adr","gps","nom_commune","latitude_com","longitude_com"]]
df_caracteristique_geocode['adr_full'] = df_caracteristique_geocode['adr']+' '+df_caracteristique_geocode['nom_commune']

In [ ]:
df_caracteristiques_complet["lat"]==0

0          False
1          False
2          False
3          False
4          False
           ...
1187857    False
1187858    False
1187859    False
1187860    False
1187861    False
Name: lat, Length: 1187862, dtype: bool

In [ ]:

df_caracteristiques_complet[(df_caracteristiques_complet["lat"]==0) | (df_caracteristiques_complet["long"]==0)].Num_Acc.count()

60803

In [ ]:
df_caracteristique_geocode = df_caracteristique_geocode[['adr_full']].reset_index()
df_caracteristique_geocode = df_caracteristique_geocode.dropna(axis=0)

In [ ]:
df_caracteristique_geocode.head()

Empty DataFrame
Columns: [index, adr_full]
Index: []

In [ ]:
df_caracteristiques_complet.shape

(1187862, 25)

In [ ]:
# Chargement dataset Global
#df_caracteristiques_1 =pd.read_csv(pathData + 'caracteristiques_2005_to_2023.csv', sep=',')

<ipython-input-44-54b8f82a0e7b>:2: DtypeWarning: Columns (4,6,7,13,14,15) have mixed types. Specify dtype option on import or set low_memory=False.
  df_caracteristiques_1 =pd.read_csv(pathData + 'caracteristiques_2005_to_2023.csv', sep=',')

In [ ]:
#df_caracteristiques_1.shape

(1231695, 16)

In [ ]:
negativ_long = df_caracteristiques["long"].str.contains("-",na=False)
negativ_long = negativ_long[negativ_long == True]
negativ_long

20        True
23        True
30        True
31        True
32        True
          ...
884485    True
884498    True
884542    True
884543    True
884544    True
Name: long, Length: 44907, dtype: bool

In [ ]:
negativ_long.index

Index([    20,     23,     30,     31,     32,     36,     39,     45,     57,
           58,
       ...
       884380, 884398, 884422, 884424, 884425, 884485, 884498, 884542, 884543,
       884544],
      dtype='int64', length=44907)

In [ ]:
df_caracteristiques.iloc[negativ_long.index].long.unique()

array([' -2,97344300', ' -3,13490700', ' -4,07505900', ..., '-385700.0',
       '-354400.0', '-94900.0'], dtype=object)

In [ ]:
df_caracteristiques["long"]=df_caracteristiques["long"].str.replace(',','.')
df_caracteristiques.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1187862 entries, 0 to 1187861
Data columns (total 25 columns):
 #   Column           Non-Null Count    Dtype
---  ------           --------------    -----
 0   Num_Acc          1187862 non-null  int64
 1   jour             1187862 non-null  int64
 2   mois             1187862 non-null  int64
 3   an               1187862 non-null  int64
 4   hrmn             1187862 non-null  object
 5   lum              1187862 non-null  int64
 6   dep_x            1187862 non-null  float64
 7   com              1187860 non-null  object
 8   agg              1187862 non-null  int64
 9   int              1187862 non-null  int64
 10  atm              1187823 non-null  float64
 11  col              1187851 non-null  float64
 12  adr              1047107 non-null  object
 13  lat              715631 non-null   object
 14  long             300173 non-null   object
 15  gps              463488 non-null   object
 16  com_insee_temp   1187862 non-null  object
 17  com_insee        1187862 non-null  object
 18  nom_commune      258124 non-null   object
 19  dep_y            258124 non-null   object
 20  nom_departement  258124 non-null   object
 21  code_region      258124 non-null   float64
 22  nom_region       258124 non-null   object
 23  latitude_com     258118 non-null   float64
 24  longitude_com    258118 non-null   float64
dtypes: float64(6), int64(7), object(12)
memory usage: 226.6+ MB

In [ ]:
df_caracteristiques.long

0          2.32347100
1          2.42868146
2          2.40655000
3          2.44687575
4          2.49217000
              ...
1187857           NaN
1187858           NaN
1187859           NaN
1187860           NaN
1187861           NaN
Name: long, Length: 1187862, dtype: object

In [ ]:

df_caracteristiques["long"] = df_caracteristiques["long"].fillna(0).replace("-", 0).astype(float)

In [ ]:
df_caracteristiques["lat"]=df_caracteristiques["lat"].str.replace(',','.')
df_caracteristiques.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1187862 entries, 0 to 1187861
Data columns (total 25 columns):
 #   Column           Non-Null Count    Dtype
---  ------           --------------    -----
 0   Num_Acc          1187862 non-null  int64
 1   jour             1187862 non-null  int64
 2   mois             1187862 non-null  int64
 3   an               1187862 non-null  int64
 4   hrmn             1187862 non-null  object
 5   lum              1187862 non-null  int64
 6   dep_x            1187862 non-null  float64
 7   com              1187860 non-null  object
 8   agg              1187862 non-null  int64
 9   int              1187862 non-null  int64
 10  atm              1187823 non-null  float64
 11  col              1187851 non-null  float64
 12  adr              1047107 non-null  object
 13  lat              262081 non-null   object
 14  long             1187862 non-null  float64
 15  gps              463488 non-null   object
 16  com_insee_temp   1187862 non-null  object
 17  com_insee        1187862 non-null  object
 18  nom_commune      258124 non-null   object
 19  dep_y            258124 non-null   object
 20  nom_departement  258124 non-null   object
 21  code_region      258124 non-null   float64
 22  nom_region       258124 non-null   object
 23  latitude_com     258118 non-null   float64
 24  longitude_com    258118 non-null   float64
dtypes: float64(7), int64(7), object(11)
memory usage: 226.6+ MB

In [ ]:
df_caracteristiques = df_caracteristiques.astype({'lat':'float'})

In [ ]:
df_caracteristiques.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1187862 entries, 0 to 1187861
Data columns (total 25 columns):
 #   Column           Non-Null Count    Dtype
---  ------           --------------    -----
 0   Num_Acc          1187862 non-null  int64
 1   jour             1187862 non-null  int64
 2   mois             1187862 non-null  int64
 3   an               1187862 non-null  int64
 4   hrmn             1187862 non-null  object
 5   lum              1187862 non-null  int64
 6   dep_x            1187862 non-null  float64
 7   com              1187860 non-null  object
 8   agg              1187862 non-null  int64
 9   int              1187862 non-null  int64
 10  atm              1187823 non-null  float64
 11  col              1187851 non-null  float64
 12  adr              1047107 non-null  object
 13  lat              262081 non-null   float64
 14  long             1187862 non-null  float64
 15  gps              463488 non-null   object
 16  com_insee_temp   1187862 non-null  object
 17  com_insee        1187862 non-null  object
 18  nom_commune      258124 non-null   object
 19  dep_y            258124 non-null   object
 20  nom_departement  258124 non-null   object
 21  code_region      258124 non-null   float64
 22  nom_region       258124 non-null   object
 23  latitude_com     258118 non-null   float64
 24  longitude_com    258118 non-null   float64
dtypes: float64(8), int64(7), object(10)
memory usage: 226.6+ MB

In [ ]:
df_caracteristiques["long"] = [(lon / 100000) if abs(lon) > 10000 else lon for lon in df_caracteristiques["long"].values]

In [ ]:

df_caracteristiques["lat"] = [(lat / 100000) if lat > 1000000 else lat for lat in df_caracteristiques["lat"].values]

In [ ]:
df_caracteristiques["long"] = df_caracteristiques["long"].astype(float)
df_caracteristiques["lat"] = df_caracteristiques["lat"].fillna(0).astype(float)

In [ ]:
# Nombre de longitude et latitude à 0
df_caracteristiques[(df_caracteristiques["lat"]==0) | (df_caracteristiques["long"]==0)].Num_Acc.count()

925781

In [ ]:

df_caracteristiques_complet = df_caracteristiques.copy()

In [ ]:
df_caracteristiques_complet["lat"] = np.where(((df_caracteristiques_complet["lat"]==0)
                         | (df_caracteristiques_complet["long"]==0))
                         & (df_caracteristiques_complet["adr"].isnull()), df_caracteristiques_complet["latitude_com"], df_caracteristiques_complet["lat"])
df_caracteristiques_complet["long"] = np.where(((df_caracteristiques_complet["lat"]==0)
                         | (df_caracteristiques_complet["long"]==0))
                         & (df_caracteristiques_complet["adr"].isnull()), df_caracteristiques_complet["longitude_com"], df_caracteristiques_complet["long"])

In [ ]:
df_caracteristiques_complet.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1187862 entries, 0 to 1187861
Data columns (total 25 columns):
 #   Column           Non-Null Count    Dtype
---  ------           --------------    -----
 0   Num_Acc          1187862 non-null  int64
 1   jour             1187862 non-null  int64
 2   mois             1187862 non-null  int64
 3   an               1187862 non-null  int64
 4   hrmn             1187862 non-null  object
 5   lum              1187862 non-null  int64
 6   dep_x            1187862 non-null  float64
 7   com              1187860 non-null  object
 8   agg              1187862 non-null  int64
 9   int              1187862 non-null  int64
 10  atm              1187823 non-null  float64
 11  col              1187851 non-null  float64
 12  adr              1047107 non-null  object
 13  lat              1051117 non-null  float64
 14  long             1052905 non-null  float64
 15  gps              463488 non-null   object
 16  com_insee_temp   1187862 non-null  object
 17  com_insee        1187862 non-null  object
 18  nom_commune      258124 non-null   object
 19  dep_y            258124 non-null   object
 20  nom_departement  258124 non-null   object
 21  code_region      258124 non-null   float64
 22  nom_region       258124 non-null   object
 23  latitude_com     258118 non-null   float64
 24  longitude_com    258118 non-null   float64
dtypes: float64(8), int64(7), object(10)
memory usage: 226.6+ MB

In [ ]:
df_caracteristiques_complet.head()

,Num_Acc,jour,mois,an,hrmn,lum,dep_x,com,agg,int,...,gps,com_insee_temp,com_insee,nom_commune,dep_y,nom_departement,code_region,nom_region,latitude_com,longitude_com
0,202300000001,7,5,2023,06:00,1,75.0,75101,2,4,...,NaN,75.075101,75101,Paris 01,075,Paris,11.0,Île-de-France,48.862630,2.336293
1,202300000002,7,5,2023,05:30,5,94.0,94080,2,1,...,NaN,94.094080,94080,Vincennes,094,Val-de-Marne,11.0,Île-de-France,48.847373,2.437987
2,202300000003,7,5,2023,20:50,1,94.0,94022,2,3,...,NaN,94.094022,94022,Choisy-le-Roi,094,Val-de-Marne,11.0,Île-de-France,48.764315,2.417425
3,202300000004,6,5,2023,23:57,5,94.0,94078,2,1,...,NaN,94.094078,94078,Villeneuve-Saint-Georges,094,Val-de-Marne,11.0,Île-de-France,48.741381,2.448999
4,202300000005,7,5,2023,00:50,5,94.0,94068,2,2,...,NaN,94.094068,94068,Saint-Maur-des-Fossés,094,Val-de-Marne,11.0,Île-de-France,48.799068,2.493865

In [ ]:
df_caracteristique_geocode = df_caracteristiques_complet.loc[((df_caracteristiques_complet["lat"]==0)
                         | (df_caracteristiques_complet["long"]==0)),["lat","long","adr","gps","nom_commune","latitude_com","longitude_com"]]

In [ ]:
df_caracteristique_geocode.head()

,lat,long,adr,gps,nom_commune,latitude_com,longitude_com
259416,0.0,0.0,AVENUE DU BOIS,NaN,NaN,NaN,NaN
259434,0.0,0.0,AVENUE YVES DUBOIS DE LA,NaN,NaN,NaN,NaN
259489,0.0,0.0,Intersection D975 et D.3,M,NaN,NaN,NaN
260762,0.0,0.0,RD 538A QT FOISSONNETS,M,NaN,NaN,NaN
260766,0.0,0.0,LA PIMPIE,M,NaN,NaN,NaN

In [ ]:
df_caracteristique_geocode[df_caracteristique_geocode.nom_commune.notnull()].head()

Empty DataFrame
Columns: [lat, long, adr, gps, nom_commune, latitude_com, longitude_com]
Index: []

In [ ]:
df_caracteristique_geocode = df_caracteristiques_complet.loc[((df_caracteristiques_complet["lat"]==0)
                         | (df_caracteristiques_complet["long"]==0)),["lat","long","adr","gps","nom_commune","latitude_com","longitude_com"]]
df_caracteristique_geocode['adr_full'] = df_caracteristique_geocode['adr']+' '+df_caracteristique_geocode['nom_commune']
df_caracteristique_geocode = df_caracteristique_geocode[['adr_full']].reset_index()
df_caracteristique_geocode = df_caracteristique_geocode.dropna(axis=0)

In [ ]:
df_caracteristique_geocode.info()

<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   index     0 non-null      int64
 1   adr_full  0 non-null      object
dtypes: int64(1), object(1)
memory usage: 0.0+ bytes

In [ ]:
import geopandas as gpd
import geopy.geocoders
geopy.geocoders.options.default_user_agent = "lebris.gilles76y@gmail.com"

result_test_geocode = gpd.tools.geocode("77 route de darnetal Rouen", provider='nominatim')
result_test_geocode

def geocoder_points(row):
    try:
        point = gpd.tools.geocode(row, provider='nominatim').geometry.iloc[0]
        return pd.Series({'lat': point.y, 'long': point.x})
    except:
        return None

df_caracteristique_geocode['adr_full'] = df_caracteristique_geocode['adr']+' '+df_caracteristique_geocode['nom_commune']
df_caracteristique_geocode[['lat', 'long']] = df_caracteristique_geocode.apply(lambda x: geocoder_points(x['adr_full']), axis=1)

print("{}% des adresses ont été géocodées avec succès.".format(
    (1 - sum(np.isnan(df_caracteristique_geocode["lat"])) / len(df_caracteristique_geocode)) * 100))

KeyError: 'adr'

925 781 de données n'ont pas de longitude ou de latitude de renseigné
Je vais essayer de remplir ses données manquantes avec la commune renseignée