# Chargement des datasets des lieux des accidents

In [ ]:
from google.colab import drive
drive.mount('/content/drive',force_remount=True)

Mounted at /content/drive

In [ ]:
# liste du r√©pertoire
!ls "/content/drive/MyDrive/Accidents/datas"

drive = True
path = "/content/drive/MyDrive/Accidents/"
pathData = "/content/drive/MyDrive/Accidents/datas/"
pathDataRegroupement = "/content/drive/MyDrive/Accidents/datas/Regroupement/"

2009.csv
2010.csv
2011.csv
2012.csv
2013.csv
2014.csv
2015.csv
2016.csv
2017.csv
2018.csv
2019.csv
2020.csv
2021.csv
caracteristiques_2005.csv
caracteristiques_2006.csv
caracteristiques_2007.csv
caracteristiques_2008.csv
caracteristiques_2009.csv
caracteristiques_2010.csv
caracteristiques_2011.csv
caracteristiques_2012.csv
caracteristiques_2013.csv
caracteristiques_2014.csv
caracteristiques_2015.csv
caracteristiques_2016.csv
caracteristiques_2017.csv
caracteristiques_2018.csv
caracteristiques_2019.csv
caracteristiques_2020.csv
caracteristiques_2021.csv
caracteristiques_2022.csv
caracteristiques_2023.csv
description-de-la-liste-des-vehicules-immatricules-impliques-dans-les-accidents-corporels.pdf
description-des-bases-de-donnees-onisr-annees-2005-a-2018.pdf
description-des-bases-de-donnees-onisr-annees-2005-a-2020.pdf
lieux_2005.csv
lieux_2005_to_2023.csv
lieux_2006.csv
lieux_2007.csv
lieux_2008.csv
lieux_2009.csv
lieux_2010.csv
lieux_2011.csv
lieux_2012.csv
lieux_2013.csv
lieux_2014.csv
lieux_2015.csv
lieux_2016.csv
lieux_2017.csv
lieux_2018.csv
lieux_2019.csv
lieux_2020.csv
lieux_2021.csv
lieux_2022.csv
lieux_2023.csv
Regroupement
usagers_2005.csv
usagers_2006.csv
usagers_2007.csv
usagers_2008.csv
usagers_2009.csv
usagers_2010.csv
usagers_2011.csv
usagers_2012.csv
usagers_2013.csv
usagers_2014.csv
usagers_2015.csv
usagers_2016.csv
usagers_2017.csv
usagers_2018.csv
usagers_2019.csv
usagers_2020.csv
usagers_2021.csv
usagers_2022.csv
usagers_2023.csv
vehicules_2005.csv
vehicules_2006.csv
vehicules_2007.csv
vehicules_2008.csv
vehicules_2009.csv
vehicules_2010.csv
vehicules_2011.csv
vehicules_2012.csv
vehicules_2013.csv
vehicules_2014.csv
vehicules_2015.csv
vehicules_2016.csv
vehicules_2017.csv
vehicules_2018.csv
vehicules_2019.csv
vehicules_2020.csv
vehicules_2021.csv
vehicules_2022.csv
vehicules_2023.csv

In [ ]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
lieux_2023 =pd.read_csv(pathData + 'lieux_2023.csv', sep=';',low_memory=False)

In [ ]:
lieux_2023.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70860 entries, 0 to 70859
Data columns (total 18 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Num_Acc  70860 non-null  int64
 1   catr     70860 non-null  int64
 2   voie     58113 non-null  object
 3   v1       70860 non-null  int64
 4   v2       5884 non-null   object
 5   circ     70860 non-null  int64
 6   nbv      70860 non-null  object
 7   vosp     70860 non-null  int64
 8   prof     70860 non-null  int64
 9   pr       70860 non-null  object
 10  pr1      70860 non-null  object
 11  plan     70860 non-null  int64
 12  lartpc   31 non-null     object
 13  larrout  70860 non-null  object
 14  surf     70860 non-null  int64
 15  infra    70860 non-null  int64
 16  situ     70860 non-null  int64
 17  vma      70860 non-null  int64
dtypes: int64(11), object(7)
memory usage: 9.7+ MB

In [ ]:
lieux_2023.head()

,Num_Acc,catr,voie,v1,v2,circ,nbv,vosp,prof,pr,pr1,plan,lartpc,larrout,surf,infra,situ,vma
0,202300000001,4,RUE DE RIVOLI,0,NaN,1,2,0,1,-1,-1,1,NaN,-1,2,0,1,30
1,202300000001,4,RUE SAINT FLORENTIN,0,NaN,1,1,0,1,-1,-1,1,NaN,-1,2,0,1,30
2,202300000002,3,120,0,NaN,2,3,2,1,-1,-1,1,NaN,-1,2,0,1,50
3,202300000003,3,5,0,NaN,2,4,0,1,1,0,1,NaN,-1,2,5,1,50
4,202300000003,3,87,0,NaN,2,4,0,1,1,0,1,NaN,-1,2,5,1,50

In [ ]:
lieux_2022 = pd.read_csv(pathData + 'lieux_2022.csv', sep=';',low_memory=False)
lieux_2021 = pd.read_csv(pathData + 'lieux_2021.csv', sep=';',low_memory=False)
lieux_2020 = pd.read_csv(pathData + 'lieux_2020.csv', sep=';',low_memory=False)
lieux_2019 = pd.read_csv(pathData + 'lieux_2019.csv', sep=';',low_memory=False)

In [ ]:
#lieux_2022 = lieux_2022[['Num_Acc','catr','voie','v1','v2','circ','nbv','pr','pr1','vosp','prof','plan','lartpc','larrout','surf','infra','situ','env1']]
lieux_2023 = pd.concat([lieux_2023,lieux_2022], axis=0, ignore_index=True)

In [ ]:
lieux_2023.Num_Acc.value_counts()
#202300035508

Num_Acc
202300035508    5
202300046485    4
202300054010    4
202300007795    4
202300015235    4
               ..
202300044231    1
202300044230    1
202300044229    1
202300044228    1
202200055302    1
Name: count, Length: 110124, dtype: int64

In [ ]:
lieux_2023_test = lieux_2023[lieux_2023.Num_Acc == 202300035508]
#202300035508

In [ ]:
lieux_2023_test.head()

,Num_Acc,catr,voie,v1,v2,circ,nbv,vosp,prof,pr,pr1,plan,lartpc,larrout,surf,infra,situ,vma
45929,202300035508,4,BOULEVARD DE BEAUSEJOUR,0,NaN,1,0,0,1,0,0,1,NaN,-1,1,0,1,30
45930,202300035508,4,BOULEVARD EMILE AUGIER,0,NaN,3,2,0,1,-1,-1,1,NaN,-1,1,9,1,50
45931,202300035508,4,CHAUSSEE LA MUETTE,0,NaN,3,1,3,1,-1,-1,1,NaN,-1,1,6,1,50
45932,202300035508,4,RUE D ANDIGNE,0,NaN,1,1,0,1,0,0,1,NaN,-1,1,0,1,30
45933,202300035508,4,RUE LARGILLIERE,0,NaN,2,2,0,1,0,0,1,NaN,-1,1,0,1,30

In [ ]:
lieux_2023 = pd.concat([lieux_2023,lieux_2021], axis=0, ignore_index=True)

In [ ]:
lieux_2023 = pd.concat([lieux_2023,lieux_2020], axis=0, ignore_index=True)

In [ ]:
lieux_2023 = pd.concat([lieux_2023,lieux_2019], axis=0, ignore_index=True)

In [ ]:
lieux_2023.shape

(289264, 18)

In [ ]:
lieux_2018 =pd.read_csv(pathData + 'lieux_2018.csv', encoding = "ISO-8859-1", quotechar='"',low_memory=False)
lieux_2017 =pd.read_csv(pathData + 'lieux_2017.csv', encoding = "ISO-8859-1", quotechar='"',low_memory=False)
lieux_2016 =pd.read_csv(pathData + 'lieux_2016.csv', encoding = "ISO-8859-1", quotechar='"',low_memory=False)
lieux_2015 =pd.read_csv(pathData + 'lieux_2015.csv', encoding = "ISO-8859-1", quotechar='"',low_memory=False)
lieux_2014 =pd.read_csv(pathData + 'lieux_2014.csv', encoding = "ISO-8859-1", quotechar='"',low_memory=False)
lieux_2013 =pd.read_csv(pathData + 'lieux_2013.csv', encoding = "ISO-8859-1", quotechar='"',low_memory=False)
lieux_2012 =pd.read_csv(pathData + 'lieux_2012.csv', encoding = "ISO-8859-1", quotechar='"',low_memory=False)
lieux_2011 =pd.read_csv(pathData + 'lieux_2011.csv', encoding = "ISO-8859-1", quotechar='"',low_memory=False)
lieux_2010 =pd.read_csv(pathData + 'lieux_2010.csv', encoding = "ISO-8859-1", quotechar='"',low_memory=False)
lieux_2009 =pd.read_csv(pathData + 'lieux_2009.csv', sep=",",encoding = "ISO-8859-1", quotechar='"',low_memory=False)
lieux_2008 =pd.read_csv(pathData + 'lieux_2008.csv', encoding = "ISO-8859-1", quotechar='"',low_memory=False)
lieux_2007 =pd.read_csv(pathData + 'lieux_2007.csv', encoding = "ISO-8859-1", quotechar='"',low_memory=False)
lieux_2006 =pd.read_csv(pathData + 'lieux_2006.csv', encoding = "ISO-8859-1", quotechar='"',low_memory=False)
lieux_2005 =pd.read_csv(pathData + 'lieux_2005.csv', encoding = "ISO-8859-1", quotechar='"',low_memory=False)

In [ ]:

lieux_2009 =pd.read_csv(pathData + 'lieux_2009.csv', sep=",",encoding = "ISO-8859-1", quotechar='"',low_memory=False)

In [ ]:
lieux_2009.head()

,Num_Acc,catr,voie,v1,v2,circ,nbv,pr,pr1,vosp,prof,plan,lartpc,larrout,surf,infra,situ,env1
0,200900000001,3,125.0,NaN,NaN,2.0,2.0,7.0,0.0,0.0,1.0,1.0,0.0,52.0,1.0,0.0,1.0,0.0
1,200900000002,3,878.0,NaN,NaN,2.0,2.0,21.0,800.0,0.0,3.0,3.0,0.0,62.0,2.0,0.0,1.0,0.0
2,200900000003,3,4.0,NaN,NaN,2.0,3.0,22.0,524.0,0.0,1.0,1.0,47.0,72.0,2.0,0.0,1.0,0.0
3,200900000004,3,775.0,NaN,NaN,2.0,2.0,23.0,150.0,0.0,1.0,1.0,0.0,63.0,1.0,0.0,3.0,0.0
4,200900000005,3,41.0,NaN,NaN,2.0,2.0,13.0,500.0,0.0,1.0,1.0,0.0,40.0,1.0,0.0,1.0,0.0

In [ ]:
lieux_2023 = pd.concat([lieux_2023,lieux_2018], axis=0, ignore_index=True)
lieux_2023 = pd.concat([lieux_2023,lieux_2017], axis=0, ignore_index=True)
lieux_2023 = pd.concat([lieux_2023,lieux_2016], axis=0, ignore_index=True)
lieux_2023 = pd.concat([lieux_2023,lieux_2015], axis=0, ignore_index=True)
lieux_2023 = pd.concat([lieux_2023,lieux_2014], axis=0, ignore_index=True)
lieux_2023 = pd.concat([lieux_2023,lieux_2013], axis=0, ignore_index=True)
lieux_2023 = pd.concat([lieux_2023,lieux_2012], axis=0, ignore_index=True)
lieux_2023 = pd.concat([lieux_2023,lieux_2011], axis=0, ignore_index=True)
lieux_2023 = pd.concat([lieux_2023,lieux_2010], axis=0, ignore_index=True)
lieux_2023 = pd.concat([lieux_2023,lieux_2009], axis=0, ignore_index=True)
lieux_2023 = pd.concat([lieux_2023,lieux_2008], axis=0, ignore_index=True)
lieux_2023 = pd.concat([lieux_2023,lieux_2007], axis=0, ignore_index=True)
lieux_2023 = pd.concat([lieux_2023,lieux_2006], axis=0, ignore_index=True)
lieux_2023 = pd.concat([lieux_2023,lieux_2005], axis=0, ignore_index=True)

In [ ]:
lieux_2023.shape

(1247733, 19)

In [ ]:
lieux_2023.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1247733 entries, 0 to 1247732
Data columns (total 19 columns):
 #   Column   Non-Null Count    Dtype
---  ------   --------------    -----
 0   Num_Acc  1247733 non-null  int64
 1   catr     1247732 non-null  float64
 2   voie     1123001 non-null  object
 3   v1       611909 non-null   float64
 4   v2       62508 non-null    object
 5   circ     1246159 non-null  float64
 6   nbv      1245002 non-null  object
 7   vosp     1244972 non-null  float64
 8   prof     1245784 non-null  float64
 9   pr       772249 non-null   object
 10  pr1      770430 non-null   object
 11  plan     1245452 non-null  float64
 12  lartpc   902798 non-null   object
 13  larrout  1134892 non-null  object
 14  surf     1245809 non-null  float64
 15  infra    1242325 non-null  float64
 16  situ     1242763 non-null  float64
 17  vma      289264 non-null   float64
 18  env1     953029 non-null   float64
dtypes: float64(11), int64(1), object(7)
memory usage: 180.9+ MB

In [ ]:
# Renommer la colonne secu1 en secu
lieux_2023['Num_Acc'] = lieux_2023['Num_Acc'].astype(int)

In [ ]:
lieux_2005_to_2023 = lieux_2023

In [ ]:
lieux_2005_to_2023.head()

,Num_Acc,catr,voie,v1,v2,circ,nbv,vosp,prof,pr,pr1,plan,lartpc,larrout,surf,infra,situ,vma,env1
0,202300000001,4.0,RUE DE RIVOLI,0.0,NaN,1.0,2,0.0,1.0,-1,-1,1.0,NaN,-1,2.0,0.0,1.0,30.0,NaN
1,202300000001,4.0,RUE SAINT FLORENTIN,0.0,NaN,1.0,1,0.0,1.0,-1,-1,1.0,NaN,-1,2.0,0.0,1.0,30.0,NaN
2,202300000002,3.0,120,0.0,NaN,2.0,3,2.0,1.0,-1,-1,1.0,NaN,-1,2.0,0.0,1.0,50.0,NaN
3,202300000003,3.0,5,0.0,NaN,2.0,4,0.0,1.0,1,0,1.0,NaN,-1,2.0,5.0,1.0,50.0,NaN
4,202300000003,3.0,87,0.0,NaN,2.0,4,0.0,1.0,1,0,1.0,NaN,-1,2.0,5.0,1.0,50.0,NaN

In [ ]:
lieux_2005_to_2023.to_csv(pathDataRegroupement +  'lieux_2005_to_2023.csv', index=False)

In [ ]:
# Chargement dataset Global
df_caracteristiques =pd.read_csv(pathDataRegroupement + 'caracteristiques_2005_to_2023_step1.csv', sep=',',low_memory=False)

In [ ]:
df_caracteristiques.an.unique()

array([2023, 2022, 2021, 2020, 2019, 2018, 2017, 2016, 2015, 2014, 2013,
       2011, 2012, 2010, 2009, 2008, 2007, 2006, 2005])

In [ ]:
df_caracteristiques.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1187862 entries, 0 to 1187861
Data columns (total 18 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   Num_Acc         1187862 non-null  int64
 1   jour            1187862 non-null  int64
 2   mois            1187862 non-null  int64
 3   an              1187862 non-null  int64
 4   hrmn            1187862 non-null  object
 5   lum             1187862 non-null  int64
 6   dep             1187862 non-null  float64
 7   com             1187860 non-null  object
 8   agg             1187862 non-null  int64
 9   int             1187862 non-null  int64
 10  atm             1187823 non-null  float64
 11  col             1187851 non-null  float64
 12  adr             1047107 non-null  object
 13  lat             715631 non-null   object
 14  long            715627 non-null   object
 15  gps             463488 non-null   object
 16  com_insee_temp  1187862 non-null  object
 17  com_insee       1187862 non-null  object
dtypes: float64(3), int64(7), object(8)
memory usage: 163.1+ MB

In [ ]:
# fusion
fusion = df_caracteristiques.merge(lieux_2005_to_2023, on='Num_Acc', how='left')
caracteristiques = fusion.copy()

In [ ]:
fusion.to_csv(pathDataRegroupement +  'Caracteristiques_lieux_2005_to_2023.csv', index=False)

In [ ]:
fusion.shape

(1203273, 36)